### ISSUE TITLE
Add fallback value to env()

### ISSUE THREAD

**Issue by szepeviktor** [oscarotero/env#5]
Hello @oscarotero !
Would it be possible to add a second parameter to `env($name, $defaultValue)`?

**Comment by oscarotero** [comment]
Hi. Why not simply and better performant?:

```php
$value = env($name) ?: $defaultValue;
```

**Comment by szepeviktor** [comment]
OK. I see.

**Comment by ghost** [comment]
Hi,

If you change the default value on the class, then you cannot use your solution anymore (which is NOT more performant, btw):

```php
Env::$default = 'Nothing';
$value = env($name) ?: $defaultValue;
```

`$value` will never have the `$defaultValue`, except when an environment value is converted to `null`, like the [string `"null"`](https://github.com/oscarotero/env/blob/4ab45ce5c1f2c62549208426bfa20a3d5fa008c6/src/Env.php#L80).

Allowing user to pass a local default value will be more performant, because if it does not exist, there is no conversion and the default value is then returned.

Also, it would be nice to allow the default value to be a closure that actually returns the default value.

**Comment by oscarotero** [comment]
@Arcesilas `getenv` by default returns `false` for not found values. This library returns `null`, in order to distinguish between not found variables and variables with the value `false`. The main purpose of `Env::$default` is to configure this and restore the default behavior of returning `false`.

The ability to include a default value to `env` has two problems:

- What is considered a falsy value? False can be any of `null`, `false`, `0`, `""`? All of them? What if `Env::$default = 'Nothing'`, Now `'Nothing'` is considered false too? Each use case is different so I prefer to leave this decision to the user:

- Performance. If you has to add the default value to `env`, then you have generate that value:

```php
$value = env('password', 'foo');
```

If the default value require expensive work, it has to be executed, no matter if it's needed or not.

```php
$value = env('password', generateDefaultPassword());
```

Using the PHP conditions, the default value will not be executed if the variable has value:

```php
putenv('password=foo');

//generateDefaultPassword() won't be executed
$value = env('password') ?: generateDefaultPassword();
```

You are suggesting to use a closure, so we are introducing more complexity to the function, and never will be more performant than a simple PHP condition:

```php
$value = env('password', function () { 
    return generateDefaultPassword();
});
```

Definitelly, it's not a good idea.
